CREATE SCHEMA IF NOT EXISTS proj_cov19;

USE proj_cov19;

CREATE TABLE IF NOT EXISTS 2021Jun08 (
    COV_ID INTEGER NOT NULL, COV_REG INTEGER NOT NULL, COV_EW INTEGER NOT NULL, COV_EWG INTEGER NOT NULL,
    COV_EY INTEGER NOT NULL, COV_GDR INTEGER NOT NULL, COV_AGR INTEGER NOT NULL, COV_OCC INTEGER NOT NULL,
    COV_ACM INTEGER NOT NULL, COV_OW INTEGER NOT NULL, COV_OY INTEGER NOT NULL, COV_HSP INTEGER NOT NULL,
    COV_RSV INTEGER NOT NULL, COV_RW INTEGER NOT NULL, COV_RY INTEGER NOT NULL, COV_DTH INTEGER NOT NULL,
    COV_TRM INTEGER NOT NULL, PRIMARY KEY (COV_ID)
);

LOAD DATA INFILE 'test.csv' REPLACE INTO TABLE proj_cov19.`2021Jun08` FIELDS TERMINATED BY ',' IGNORE 1 LINES;

# create tables from the src by year
CREATE TABLE IF NOT EXISTS 2021Jun08_yr20 (SELECT * FROM 2021Jun08 WHERE COV_EY = 20);
CREATE TABLE IF NOT EXISTS 2021Jun08_yr21 (SELECT * FROM 2021Jun08 WHERE COV_EY = 21);
CREATE TABLE IF NOT EXISTS 2021Jun08_yr99 (SELECT * FROM 2021Jun08 WHERE COV_EY = 99);

# create tables from the src by region
CREATE TABLE IF NOT EXISTS 2021Jun08_AC (SELECT * FROM 2021Jun08 WHERE COV_REG = 1);
CREATE TABLE IF NOT EXISTS 2021Jun08_QC (SELECT * FROM 2021Jun08 WHERE COV_REG = 2);
CREATE TABLE IF NOT EXISTS 2021Jun08_ON (SELECT * FROM 2021Jun08 WHERE COV_REG = 3);
CREATE TABLE IF NOT EXISTS 2021Jun08_PS (SELECT * FROM 2021Jun08 WHERE COV_REG = 4);
CREATE TABLE IF NOT EXISTS 2021Jun08_BY (SELECT * FROM 2021Jun08 WHERE COV_REG = 5);

# create summaries
SELECT COV_GDR, COV_AGR, COUNT(*) FROM proj_cov19.`2021Jun08_AC_icuY_dthY` GROUP BY COV_GDR, COV_AGR;
SELECT COV_GDR, COV_AGR, COUNT(*) FROM proj_cov19.`2021Jun08_AC_icuN_dthY` GROUP BY COV_GDR, COV_AGR;
SELECT COV_GDR, COV_AGR, COUNT(*) FROM proj_cov19.`2021Jun08_AC_hpN_dthY` GROUP BY COV_GDR, COV_AGR;

SELECT MAX(proj_cov19.summary_2021Jun08_AC_hpN_dthY.`COUNT(*)`) FROM proj_cov19.summary_2021Jun08_AC_hpN_dthY;

# SELECT COV_REG, COV_HSP, COV_DTH, COV_AGR, COV_GDR,
# COUNT(*) FROM proj_cov19.`2021Jun08` GROUP BY COV_REG, COV_HSP, COV_DTH, COV_AGR, COV_GDR;