# DROP TABLE IF EXISTS update_0621;

CREATE TABLE IF NOT EXISTS update_0621 (
    COV_ID INTEGER NOT NULL, COV_REG INTEGER NOT NULL, COV_EW INTEGER NOT NULL, COV_EWG INTEGER NOT NULL,
    COV_EY INTEGER NOT NULL, COV_GDR INTEGER NOT NULL, COV_AGR INTEGER NOT NULL, COV_OCC INTEGER NOT NULL,
    COV_ACM INTEGER NOT NULL, COV_OW INTEGER NOT NULL, COV_OY INTEGER NOT NULL, COV_HSP INTEGER NOT NULL,
    COV_RSV INTEGER NOT NULL, COV_RW INTEGER NOT NULL, COV_RY INTEGER NOT NULL, COV_DTH INTEGER NOT NULL,
    COV_TRM INTEGER NOT NULL, PRIMARY KEY (COV_ID)
);

SET GLOBAL local_infile = ON;

LOAD DATA LOCAL INFILE 'test.csv' REPLACE INTO TABLE proj_cov19.update_0621 FIELDS TERMINATED BY ',' IGNORE 1 LINES;

# create tables from the src by year
# CREATE TABLE IF NOT EXISTS Year_20 (SELECT * FROM update_0621 WHERE COV_EY = 20);
# CREATE TABLE IF NOT EXISTS Year_21 (SELECT * FROM update_0621 WHERE COV_EY = 21);
# CREATE TABLE IF NOT EXISTS Year_99 (SELECT * FROM update_0621 WHERE COV_EY = 99);
#
# # create tables from the src by region
# CREATE TABLE IF NOT EXISTS Reg_AC (SELECT * FROM update_0621 WHERE COV_REG = 1);
# CREATE TABLE IF NOT EXISTS Reg_QC (SELECT * FROM update_0621 WHERE COV_REG = 2);
# CREATE TABLE IF NOT EXISTS Reg_ON (SELECT * FROM update_0621 WHERE COV_REG = 3);
# CREATE TABLE IF NOT EXISTS Reg_PS (SELECT * FROM update_0621 WHERE COV_REG = 4);
# CREATE TABLE IF NOT EXISTS Reg_BY (SELECT * FROM update_0621 WHERE COV_REG = 5);