# DROP TABLE IF EXISTS update_0621;

CREATE TABLE IF NOT EXISTS update_0621 (
    COV_ID INTEGER NOT NULL, COV_REG INTEGER NOT NULL, COV_EW INTEGER NOT NULL, COV_EWG INTEGER NOT NULL,
    COV_EY INTEGER NOT NULL, COV_GDR INTEGER NOT NULL, COV_AGR INTEGER NOT NULL, COV_OCC INTEGER NOT NULL,
    COV_ACM INTEGER NOT NULL, COV_OW INTEGER NOT NULL, COV_OY INTEGER NOT NULL, COV_HSP INTEGER NOT NULL,
    COV_RSV INTEGER NOT NULL, COV_RW INTEGER NOT NULL, COV_RY INTEGER NOT NULL, COV_DTH INTEGER NOT NULL,
    COV_TRM INTEGER NOT NULL, PRIMARY KEY (COV_ID)
);

LOAD DATA LOCAL INFILE 'test.csv' REPLACE INTO TABLE update_0621 FIELDS TERMINATED BY ',' IGNORE 1 LINES;
